<?php

/**
 * @file
 * Contains crediwireprojecttimemanager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function crediwireprojecttimemanager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the crediwireprojecttimemanager module.
    case 'help.page.crediwireprojecttimemanager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CrediWire Developer assignment') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function crediwireprojecttimemanager_theme() {
  return [
    'crediwireprojecttimemanager' => [
      'render element' => 'children',
    ],
  ];
}
