<?php

/**
 * @file
 * Contains crediwireprojecttimemanager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function crediwireprojecttimemanager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the crediwireprojecttimemanager module.
    case 'help.page.crediwireprojecttimemanager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CrediWire Developer assignment') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function crediwireprojecttimemanager_theme() {
  return [
    'crediwireprojecttimemanager' => [
      'render element' => 'children',
    ],
  ];
}


function crediwireprojecttimemanager_page_attachments(array &$page)
{
     $page['#attached']['library'][] = 'crediwireprojecttimemanager/crediwireprojecttimemanager_css';
}


function crediwireprojecttimemanager_install(){
  $item = \Drupal\menu_link_content\Entity\MenuLinkContent::create([
    'link' => ['uri' => 'internal:/admin/crediwire/project_manager'],
    'title' => 'Project Manager',
    'menu_name' => 'admin',
  ]);
  $item->save();
}